### PR TITLE
Feat: type inference + text operators

### PR DESCRIPTION
**Pull request by sverben**
This relies on https://github.com/leaphy-robotics/leaphy-blocks/pull/43

### CODE REVIEW

**Comment by sverben** [comment]
The commit message is incorrect, it should be feat: type inference + text operators

**Review by rmoesbergen — APPROVED** [review]
blocks bump niet vergeten

**Review by koen1711 — CHANGES_REQUESTED** [review]
it only seems to work for void and double, returning strings, bools or something like that doesn't work

**Comment by sverben** [comment]
only applies to subprograms

**Review by koen1711 — APPROVED** [review]

**Comment by koen1711** [comment]
works with pr at https://github.com/leaphy-robotics/leaphy-blocks/pull/44

**Pull request merged**
