### PR TITLE
Update blockly-editor.effects.ts

### PR DESCRIPTION
**Pull request by JeftadeGraaf**
icm 10-standaard-google-blocks-uit-blocks-repo-verwijderen.

### CODE REVIEW

**Review by koen1711 — CHANGES_REQUESTED** [review]
Now you still have duplicates because in blocks you also define these blocks

**Comment by JeftadeGraaf** [comment]
I have changed some things around, now it is working without bugs. I could not find a fix for the styling issue.

The style component in the definition of blocks is not using the same category's as we are using. For example, logic_operation has style logic_blocks while most other blocks in the category numbers are using the style math_blocks. You could maybe fix this by changing the style before the blocks are defined. I could not find a fix, maybe some of you can?

**Comment by JeftadeGraaf** [comment]
For now I have just overwritten some blocks to have the situation_blocks style. They are still hardcoded instead of using the blockly library. When you are ready to accept this PR, dont forget to also update the npm package with it. You can change the merge conflicts in package.json and yarn.lock

**Comment by rmoesbergen** [comment]
already done in a different PR.

**Pull request closed without merging**
